baseURL = 'http://example.com'
languageCode = 'en-us'
title = 'Aleksander Claney - Software Developer'
disableKinds = ["taxonomy", "term", "section", "page"]

[params]
  author = "Aleksander Claney"
  description = "Java Software Developer"
  resume_url = "/resume.pdf"  # PDF resume file path
  github = "https://github.com/meritant"
  linkedin = "www.linkedin.com/in/aleks-claney"
  email = "aleksclaney@gmail.com"

  [params.hero]
    title = "Aleksander Claney"
    subtitle = "Software Developer"
    description = "Currently building web applications with modern technologies"

  [params.about]
    image = "/images/laptop.gif"  # Will fallback to placeholder if not found
    paragraphs = [
      "Software developer passionate about building innovative solutions, currently making a transition from a 11-year career in transportation. During my time as a truck driver, I developed exceptional problem-solving, customer service, communication abilities, and a reputation for reliability – now complemented by programming expertise. Currently developing innovative software solutions that bridge technical requirements with practical business needs."
    ]

  [css]
  [css.PostCSS]
    config = "postcss.config.js"


[menu]
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 1
  [[menu.main]]
    name = "Portfolio"
    url = "#portfolio"
    weight = 2
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 4